name: Test de workflow

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"
    
jobs:
  main_job:
    runs-on: ubuntu-latest
    steps:
      - name: Verification du code source
        run: echo "Recuperation du code source"
      - name: sortie sans erreur
        run: echo "Verification terminees"
